secrets:
  awsAccessKey: "<INSERT>"
  awsAccessSecretKey: "<INSERT>"

image:
  # Update to the correct one
  repository: 777779114298.dkr.ecr.eu-central-1.amazonaws.com/url-shortener

dynamodb:
  endpoint: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
